redis:
  host: r-j6c311e4daee1334.redis.rds.aliyuncs.com
  port: 6379
  password: HlvwcDQK5TDzv2Mo
  timeout: 5000
  pool:
    minIdle: 50
    maxIdle: 50
    maxTotal: 200
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true


ossConstant:
  bucketBase: hotcoin-hk-static
  accessKey: LTAI9aBzu59pCcSd
  secretKey: TwiWldHgibG2TI5r1UzeyCHHFOAkRp
  ossEndpoint: http://oss-cn-hongkong.aliyuncs.com

aliyun:
  mq:
    accessKey: LTAI9aBzu59pCcSd
    secretKey: TwiWldHgibG2TI5r1UzeyCHHFOAkRp
    onsAddr: http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal
    topic:
      entrust_state: SG_HOTCOIN_HK_ENTRUST_STATE
      user_action: SG_HOTCOIN_HK_USER_ACTION
      admin_action: SG_HOTCOIN_HK_ADMIN_ACTION
      validate: SG_HOTCOIN_HK_VALIDATE
      score: SG_HOTCOIN_HK_SCORE
    pid:
      entrustState: PID_SG_HOTCOIN_HK_ENTRUST_STATE
      validate: PID_SG_HOTCOIN_HK_VALIDATE
      score: PID_SG_HOTCOIN_HK_SCORE
      userAction: PID_SG_HOTCOIN_HK_USER_ACTION
      adminAction: PID_SG_HOTCOIN_HK_ADMIN_ACTION
    cid:
      entrustState: CID_SG_HOTCOIN_HK_ENTRUST_STATE
      validate: CID_SG_HOTCOIN_HK_VALIDATE
      score: CID_SG_HOTCOIN_HK_SCORE
      userAction: CID_SG_HOTCOIN_HK_USER_ACTION
      adminAction: CID_SG_HOTCOIN_HK_ADMIN_ACTION