spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://drdshgjho459v9r0.drds.aliyuncs.com:3306/hotcoin?useUnicode=true&characterEncoding=utf-8
    username: hotcoin
    password: ALz2UpVc6VZp11tY
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 300
    minIdle: 300
    maxActive: 500
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

redis:
  host: r-j6c311e4daee1334.redis.rds.aliyuncs.com
  port: 6379
  password: HlvwcDQK5TDzv2Mo
  timeout: 5000
  pool:
    minIdle: 100
    maxIdle: 100
    maxTotal: 500
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
