spring:
  datasource:
    name:
    url: jdbc:mysql://rm-t4n282wc9ikx3877x1o.mysql.singapore.rds.aliyuncs.com:3306/hot_coin_hsf?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Tubao502
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 50
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


redis:
  host: dev.redis.net
  port: 6379
  #password: MoXbua9TmsG94qbGS6hq
  timeout: 5000
  pool:
    minIdle: 50
    maxIdle: 50
    maxTotal: 200
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
